[package]
name = "fastgui-render-mtl"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fastgui-app = { path = "../fastgui-app" }
fastgui-chrome = { path = "../fastgui-chrome" }
fastgui-core = { path = "../fastgui-core" }
crossbeam-channel = "0.5"
raw-window-handle = "0.6"
winit = "0.30"
thiserror = "2"
objc2 = "0.5"
objc2-foundation = { version = "0.2", features = ["all"] }
objc2-app-kit = { version = "0.2", features = ["all"] }
objc2-quartz-core = { version = "0.2", features = ["all"] }
objc2-metal = { version = "0.2", features = ["all"] }
