[package]
name = "fastgui-render-vk"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fastgui-chrome = { path = "../fastgui-chrome" }
fastgui-core = { path = "../fastgui-core" }
crossbeam-channel = "0.5"
ash = { version = "0.38", default-features = false, features = ["loaded", "debug"] }
ash-window = "0.13"
raw-window-handle = "0.6"
winit = "0.30"
thiserror = "2"
