[package]
name = "fastgui-py"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "_fastgui"
crate-type = ["cdylib"]

[dependencies]
fastgui-core = { path = "../fastgui-core" }
fastgui-interop-cuda = { path = "../fastgui-interop-cuda" }
pyo3 = { version = "0.29", features = ["extension-module"] }

[target.'cfg(target_os = "macos")'.dependencies]
fastgui-render-mtl = { path = "../fastgui-render-mtl" }

[target.'cfg(not(target_os = "macos"))'.dependencies]
fastgui-render-vk = { path = "../fastgui-render-vk" }
